export const chart1data = {
  carbodata: [
    {
      month: "jan",
      air: 45,
      rail: 40,
      road: 22,
      sea: 30,
      emission: 45,
    },
    {
      month: "feb",
      air: 30,
      rail: 28,
      road: 46,
      sea: 10,
      emission: 45,
    },
    {
      month: "mar",
      air: 45,
      rail: 88,
      road: 66,
      sea: 45,
      emission: 45,
    },
    {
      month: "apr",
      air: 30,
      rail: 80,
      road: 45,
      sea: 20,
      emission: 45,
    },
    {
      month: "may",
      air: 41,
      rail: 80,
      road: 45,
      sea: 10,
      emission: 45,
    },
    {
      month: "jun",
      air: 30,
      rail: 80,
      road: 45,
      sea: 40,
      emission: 80,
    },
  ],
};
export const chart2data = {
  carbodata: [
    {
      day: "mon",
      air: 45,
      rail: 40,
      road: 22,
      sea: 30,
    },
    {
      day: "tue",
      air: 30,
      rail: 28,
      road: 46,
      sea: 10,
    },
    {
      day: "wed",
      air: 45,
      rail: 88,
      road: 66,
      sea: 45,
    },
    {
      day: "thurs",
      air: 30,
      rail: 80,
      road: 45,
      sea: 20,
    },
    {
      day: "fri",
      air: 41,
      rail: 80,
      road: 45,
      sea: 10,
    },
    {
      day: "sat",
      air: 30,
      rail: 80,
      road: 45,
      sea: 40,
    },
  ],
};
